FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy package files and install deps
COPY package*.json ./
RUN npm install

# Copy rest of the project
COPY . .

# Expose port
EXPOSE 5001

# Start the app
CMD ["node", "src/server.js"]